### ISSUE TITLE
Will the paper be released in days to come?

### ISSUE THREAD

**Issue by sylvain-wei** [HITsz-TMG/awesome-llm-attributions#1]
Thanks to your contribution, and your work is awesome and helpful! I didn't find your paper on the internet. So I wanna know when will the paper be released?

**Comment by crazyofapple** [comment]
Our preprint "A Survey of Large Language Models Attribution" is now available at https://arxiv.org/abs/2311.03731. Please note that it is a work in progress; stay tuned for updates. We will update you posted.
