### ISSUE TITLE
Add paper request

### ISSUE THREAD

**Issue by mukhal** [HITsz-TMG/awesome-llm-attributions#5]
Hello,

Thank you for the amazing repo. We recently had an [arxiv](https://arxiv.org/abs/2404.01019) paper titled **Source-Aware Training Enables Knowledge Attribution in Language Models** and would appreciate it if it was included in your repo/survey. 
I think it fits under the category **Attribution Systems & End-to-End Attribution Models**. 

Thank you!

**Comment by crazyofapple** [comment]
Hi, please open a new pull request with this paper and I will merge it. Thanks!
